### ISSUE TITLE
Pre-loading already selected daypart

### ISSUE THREAD

**Issue by Piusn** [cichys/angular-dayparts#1]
Any ideas on how I can preload already selected dayparts

**Comment by cichys** [comment]
Hi, you can't at the moment. it's in my todo list, I will do it in next days.

**Comment by Piusn** [comment]
Thanks, am i allowed to extend it to support it? Nice directive. Thanks

**Comment by cichys** [comment]
Sure you can fork it and make a pull request :)

**Comment by cichys** [comment]
Ok i've done it with the version 0.2.0

**Comment by cichys** [comment]
Just add in your options
selected: ['monday-11', 'monday-12']
